app1/urls.py
from app1.views import *

from django.urls import path

app_name='mustang1967'

urlpatterns=[
    path('new/',new,name='new'),
]

app2/urls.py
from app2.views import *

from django.urls import path

app_name='muscle'

urlpatterns=[
    path('old/',old,name='old'),
]

specificurl/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),

]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def new(request):
    return render(request,'new.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def old(request):
    return render(request,'old.html')
 
 

templates/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>dont know what happened</h1>
        <a href="{% url 'muscle:old' %}"><h1>click</h1></a>
    </center>
</body>
</html>

templates/old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>share with me i can make it clear</h1>
        <a href="{% url 'mustang1967:new' %}"><h1>click</h1></a>
    </center>
</body>
</html>